// supabase/functions/send-push/index.ts
//
// Supabase Edge Function that delivers Web Push notifications.
// Triggered by a Database Webhook on `public.notifications` (event: INSERT).
//
// Reads all push_subscriptions for the recipient `user_id`, signs each push
// with VAPID using the JOSE library (Deno-friendly, no native crypto).
//
// Required Edge Function secrets (set with `supabase secrets set ...`):
//   VAPID_PUBLIC_KEY
//   VAPID_PRIVATE_KEY
//   VAPID_SUBJECT          (e.g. mailto:admin@alfatwin.app)
//   SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//
// Webhook payload shape from Supabase (when configured for INSERT on
// public.notifications):
//   {
//     "type": "INSERT",
//     "table": "notifications",
//     "record": { "id": "...", "user_id": "...", "tipo": "...", "titulo": "...",
//                 "mensaje": "...", "link": "/...", "leido": false, "created_at": "..." },
//     "old_record": null,
//     ...
//   }

// deno-lint-ignore-file no-explicit-any
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { importPKCS8, importJWK, SignJWT } from 'https://esm.sh/jose@5.9.6';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const VAPID_PUBLIC = Deno.env.get('VAPID_PUBLIC_KEY')!;
const VAPID_PRIVATE = Deno.env.get('VAPID_PRIVATE_KEY')!;
const VAPID_SUBJECT = Deno.env.get('VAPID_SUBJECT') || 'mailto:admin@alfatwin.app';

const admin = createClient(SUPABASE_URL, SERVICE_ROLE, {
  auth: { persistSession: false, autoRefreshToken: false },
});

// ---------- helpers ----------

function b64urlToUint8(b64: string): Uint8Array {
  const pad = '='.repeat((4 - (b64.length % 4)) % 4);
  const raw = atob((b64 + pad).replace(/-/g, '+').replace(/_/g, '/'));
  return Uint8Array.from(raw, (c) => c.charCodeAt(0));
}

function uint8ToB64url(arr: Uint8Array): string {
  let s = '';
  for (const b of arr) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

async function importVapidPrivateJwk() {
  // The VAPID private key generated by our Python script is a 32-byte
  // big-endian scalar (P-256). We need to convert that to a JWK alongside
  // the matching public key (uncompressed point: 0x04 || X(32) || Y(32)).
  const dB64 = VAPID_PRIVATE;
  const pubBytes = b64urlToUint8(VAPID_PUBLIC); // 65 bytes: 0x04 || X || Y
  if (pubBytes.length !== 65 || pubBytes[0] !== 0x04) {
    throw new Error('VAPID_PUBLIC_KEY must be uncompressed P-256 (65 bytes)');
  }
  const x = uint8ToB64url(pubBytes.slice(1, 33));
  const y = uint8ToB64url(pubBytes.slice(33, 65));
  return await importJWK(
    { kty: 'EC', crv: 'P-256', x, y, d: dB64, ext: true },
    'ES256',
  );
}

async function buildVapidJwt(audience: string) {
  const key = await importVapidPrivateJwk();
  return await new SignJWT({})
    .setProtectedHeader({ alg: 'ES256', typ: 'JWT' })
    .setSubject(VAPID_SUBJECT)
    .setAudience(audience)
    .setExpirationTime('12h')
    .sign(key as any);
}

async function deriveContentKeys(p256dhB64: string, authB64: string, payload: Uint8Array) {
  // RFC 8291 (aes128gcm) implementation.
  const subscriberPub = b256dhToCryptoKey(p256dhB64);
  const authSecret = b64urlToUint8(authB64);

  const local = await crypto.subtle.generateKey(
    { name: 'ECDH', namedCurve: 'P-256' },
    true,
    ['deriveBits'],
  );
  const localPubRaw = new Uint8Array(
    await crypto.subtle.exportKey('raw', local.publicKey),
  );

  const ecdhSecret = new Uint8Array(
    await crypto.subtle.deriveBits({ name: 'ECDH', public: await subscriberPub }, local.privateKey, 256),
  );

  // PRK_key = HMAC-SHA256(authSecret, ecdhSecret)
  const prkKey = await hkdfExtract(authSecret, ecdhSecret);

  // key_info = "WebPush: info" || 0x00 || ua_public || as_public
  const subscriberPubRaw = b64urlToUint8(p256dhB64); // 65 bytes
  const keyInfo = concat(
    new TextEncoder().encode('WebPush: info\0'),
    subscriberPubRaw,
    localPubRaw,
  );
  const ikm = await hkdfExpand(prkKey, keyInfo, 32);

  const salt = crypto.getRandomValues(new Uint8Array(16));
  const prk = await hkdfExtract(salt, ikm);
  const cek = await hkdfExpand(prk, new TextEncoder().encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdfExpand(prk, new TextEncoder().encode('Content-Encoding: nonce\0'), 12);

  // Plaintext: payload || 0x02 (last record marker)
  const plaintext = new Uint8Array(payload.length + 1);
  plaintext.set(payload, 0);
  plaintext[payload.length] = 0x02;

  const cekKey = await crypto.subtle.importKey('raw', cek, { name: 'AES-GCM' }, false, ['encrypt']);
  const cipher = new Uint8Array(
    await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, cekKey, plaintext),
  );

  // aes128gcm content-encoding header:
  //   salt(16) || rs(4 BE = 4096) || idlen(1 = 65) || keyid(localPubRaw 65 bytes)
  const header = new Uint8Array(16 + 4 + 1 + 65);
  header.set(salt, 0);
  header[16] = 0x00; header[17] = 0x00; header[18] = 0x10; header[19] = 0x00; // rs = 4096
  header[20] = 65;
  header.set(localPubRaw, 21);

  return concat(header, cipher);
}

async function b256dhToCryptoKey(p256dhB64: string) {
  const raw = b64urlToUint8(p256dhB64);
  return crypto.subtle.importKey('raw', raw, { name: 'ECDH', namedCurve: 'P-256' }, true, []);
}

async function hkdfExtract(salt: Uint8Array, ikm: Uint8Array): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', salt, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', key, ikm));
}

async function hkdfExpand(prk: Uint8Array, info: Uint8Array, length: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', prk, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const buf = concat(info, new Uint8Array([0x01]));
  const t1 = new Uint8Array(await crypto.subtle.sign('HMAC', key, buf));
  return t1.slice(0, length);
}

function concat(...arrays: Uint8Array[]) {
  const total = arrays.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrays) { out.set(a, off); off += a.length; }
  return out;
}

async function sendPush(sub: { endpoint: string; p256dh: string; auth: string }, payload: any) {
  const url = new URL(sub.endpoint);
  const aud = `${url.protocol}//${url.host}`;
  const jwt = await buildVapidJwt(aud);

  const body = await deriveContentKeys(
    sub.p256dh,
    sub.auth,
    new TextEncoder().encode(JSON.stringify(payload)),
  );

  const res = await fetch(sub.endpoint, {
    method: 'POST',
    headers: {
      'Content-Encoding': 'aes128gcm',
      'Content-Type': 'application/octet-stream',
      'TTL': '2419200',
      'Authorization': `vapid t=${jwt}, k=${VAPID_PUBLIC}`,
    },
    body,
  });
  return res;
}

// ---------- handler ----------

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: cors() });
  }
  try {
    const payload = await req.json();
    const record = payload?.record || payload;
    const userId: string | undefined = record?.user_id;
    if (!userId) {
      return json({ error: 'Missing user_id in record' }, 400);
    }

    const { data: subs, error } = await admin
      .from('push_subscriptions')
      .select('id, endpoint, p256dh, auth')
      .eq('user_id', userId);
    if (error) throw error;
    if (!subs || subs.length === 0) {
      return json({ ok: true, sent: 0, reason: 'no_subscriptions' });
    }

    const pushPayload = {
      title: record.titulo || 'ALFATWIN',
      body: record.mensaje || '',
      url: record.link || '/',
      tag: record.tipo || 'alfatwin',
    };

    let sent = 0;
    const expired: string[] = [];
    for (const s of subs) {
      try {
        const res = await sendPush(s, pushPayload);
        if (res.status >= 200 && res.status < 300) {
          sent++;
        } else if (res.status === 404 || res.status === 410) {
          expired.push(s.id);
        } else {
          // Log for visibility but keep going.
          console.warn('push failed', s.endpoint, res.status, await res.text().catch(() => ''));
        }
      } catch (e) {
        console.warn('push error', e);
      }
    }
    if (expired.length) {
      await admin.from('push_subscriptions').delete().in('id', expired);
    }
    return json({ ok: true, sent, expired: expired.length });
  } catch (e) {
    console.error('send-push error', e);
    return json({ error: String(e?.message || e) }, 500);
  }
});

function cors() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
  };
}

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...cors() },
  });
}
